---

- name: install nodenv
  git:
    repo: "{{ nodenv_github_base_url }}/nodenv"
    dest: ~/.nodenv
    version: "{{ nodenv_version }}"

- name: add nodenv path line to shell config file
  lineinfile:
    line: export PATH="$HOME/.nodenv/bin:$PATH"
    dest: "{{ nodenv_shell_config_file }}"

- name: add nodenv init line to shell config file
  lineinfile:
    line: eval "$(nodenv init -)"
    dest: "{{ nodenv_shell_config_file }}"

- name: install node-build
  git:
    repo: "{{ nodenv_github_base_url }}/node-build.git"
    dest: ~/.nodenv/plugins/node-build

- name: list nodenv versions
  shell: ~/.nodenv/bin/nodenv versions
  register: nodenv_installed_versions
  changed_when: false

- name: install node versions
  command: ~/.nodenv/bin/nodenv install {{ item }}
  when: "item not in nodenv_installed_versions.stdout"
  with_items: "{{ nodenv_node_versions }}"

- name: install node aliases
  git:
    repo: "{{ nodenv_github_base_url }}/nodenv-aliases.git"
    dest: ~/.nodenv/plugins/node-aliases

- name: list nodenv aliases
  command: ~/.nodenv/bin/nodenv alias --list
  register: nodenv_installed_alises
  changed_when: false

- debug: msg={{ nodenv_installed_alises }}

- name: install node aliases
  command: ~/.nodenv/bin/nodenv alias {{ item.alias }} {{ item.target }}
  when: "'{{ item.alias }} => {{ item.target }}' not in nodenv_installed_alises.stdout"
  with_items: "{{ nodenv_aliases }}"

- name: get global node version
  shell: ~/.nodenv/bin/nodenv global
  register: nodenv_current_global
  changed_when: false
  when: nodenv_global is defined

- name: set global node version
  command: ~/.nodenv/bin/nodenv global {{ nodenv_global }}
  when: nodenv_global is defined and nodenv_current_global.stdout != nodenv_global
