---
# tasks file for nrser.nodenv

- name: install nodenv
  git:
    repo: "{{ nodenv_github_base_url }}/nodenv"
    dest: ~/.nodenv
    update: "{{ nodenv_update }}"

- name: add nodenv path line to .bash_profile
  lineinfile:
    line: export PATH="$HOME/.nodenv/bin:$PATH"
    dest: ~/.bash_profile

- name: add nodenv init line to .bash_profile
  lineinfile:
    line: eval "$(nodenv init -)"
    dest: ~/.bash_profile

- name: install node-build
  git:
    repo: "{{ nodenv_github_base_url }}/node-build.git"
    dest: ~/.nodenv/plugins/node-build
    update: "{{ nodenv_update }}"

- name: install node-build
  git:
    repo: "{{ nodenv_github_base_url }}/node-build.git"
    dest: ~/.nodenv/plugins/node-build
    update: true
  when: nodenv_build_needs_update

- name: install node.js versions
  command: ~/.nodenv/bin/nodenv install {{ item }}
  when: item not in nodenv_installed_versions
  with_items: "{{ nodenv_nodes }}"

# set the global
- name: get nodenv global ruby
  shell: ~/.nodenv/bin/nodenv global
  register: nodenv_current_global
  changed_when: false
  when: nodenv_global is defined

- name: set nodenv global ruby
  command: ~/.nodenv/bin/nodenv global {{ nodenv_global }}
  when: nodenv_global is defined and nodenv_current_global.stdout != nodenv_global
